spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  application:
    name: LeetCodeSolved

project:
  version: @project.version@

server:
  port: 9002
